name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main

      - name: configure-g++
        run: |
          sudo apt-get install g++-12
          sudo update-alternatives --install /usr/bin/g++                  g++                  /usr/bin/g++-12                    100
          sudo update-alternatives --install /usr/bin/x86_64-linux-gnu-g++ x86_64-linux-gnu-g++ /usr/bin/x86_64-linux-gnu-g++-12   100

      - name: configure-gcov
        run: |
          sudo apt-get install libcapture-tiny-perl libdatetime-perl
          sudo update-alternatives --install /usr/bin/gcov                  gcov                 /usr/bin/x86_64-linux-gnu-gcov-12 100
          
      - name: configure-test
        run: |
          sudo apt-get install cowsay
          sudo npm install -g npm-check-updates

      - name: install
        run: KUNITS=1 make install lib K <<< 1

      - name: check
        run: |
          make check                                | tr -d "#" | cowsay -nW80 -fduck
          (cd /var/lib/K && ncu)               | sed '/^\s*$/d' | cowsay -nW80 -fduck

      - name: test
        run: |
          make test-c                                           | cowsay -nW160 -felephant || :
          make test            | sed '/^\s*$/d' | sed '/====/d' | cowsay -nW160 -fbud-frogs && test ${PIPESTATUS[0]} -eq 0

      - name: coverage
        run: |
          lcov -o lcov.info -c -d . --ignore-errors inconsistent --gcov-tool /usr/bin/gcov || : #> /dev/null 2>&1
          lcov -o lcov.info -r lcov.info '/usr/*' '*/include/*'                            || : #> /dev/null 2>&1
          lcov -l lcov.info                                                                | cowsay -nW80 -fdefault

      - uses: coverallsapp/github-action@main
        continue-on-error: true
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: codacy/codacy-coverage-reporter-action@master
        continue-on-error: true
        with:
          coverage-reports: lcov.info
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
